version: "3.3"


services:
  web:
    user: root
    build: .
    container_name: qdrant_demo_friends
    ports:
      - 8050:8050
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    networks:
      - local
  qdrant:
    image: qdrant/qdrant:v0.10.1
    ports:
    - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

    networks:
      - local

networks:
  local:
    driver: bridge